### ISSUE TITLE
Removing stalled comments

### ISSUE THREAD

**Issue by thypon** [brave/security-action#125]
If the comment is `Outdated` and there is no human comment, just remove the comment from the review.

**Comment by thypon** [comment]
https://github.com/brave/security-action/blob/c1a9b20d69f9869436a5ef263e5aeaa9efda9257/action.yml#LL44-L56

**Comment by bcaller** [comment]
In the GraphQL API you can access the [`outdated` field on a PullRequestReviewComment](https://docs.github.com/en/graphql/reference/objects#pullrequestreviewcomment).

Github Script uses the [REST API](https://docs.github.com/en/rest/pulls/reviews?apiVersion=2022-11-28#list-comments-for-a-pull-request-review) which doesn't expose the outdated flag. It might be possible to work it out by looking at the `position` and `original_position` fields.

**Comment by bcaller** [comment]
OK, if outdated, `position` will be `null` whereas `original_position` will be none-null.

**Comment by bcaller** [comment]
Ah github script does allow graphql
