### ISSUE TITLE
Issue with ruleset `unquoted-attribute-var.yaml`

### ISSUE THREAD

**Issue by thypon** [brave/security-action#130]
```
[semgrep] Detected a unquoted template variable as an attribute. If unquoted, a malicious actor could inject custom JavaScript handlers. To fix this, add quotes around the template expression, like this: "{{ expr }}".

Source: Brave
```

# Proposed Solution

- [ ] improve the ruleset

  - [ ] add the source attribute
  - [ ] Fix false positive case linked

**Comment by bcaller** [comment]
https://github.com/brave/security-action/blob/0512878439fbc952b70e5d17e334bfa92b1aaa7d/assets/semgrep_rules/web/unquoted-attribute-var.yaml

**Comment by bcaller** [comment]
You wanted this rule specifically for some C++ templating language right?

**Comment by thypon** [comment]
Ah, no. We use many distinct template engines, and I thought it would be helpful not to remove that but improve upon what we had with the `pattern-not-inside` I added. It found some `informative` issues on some of the repos.
