### ISSUE TITLE
Tons of false positives with https://github.com/brave/security-action/blob/main/assets/semgrep_rules/web/unquoted-attribute-var.yaml

### ISSUE THREAD

**Issue by thypon** [brave/security-action#149]
Reference: (too many)

# Proposed Solution

- [ ] Remove the rule
- [ ] Improve the rule

**Comment by thypon** [comment]
@bcaller do you think we should remove this rule or try to improve it?
@AlanBreck is having tons of false positives with this one

**Comment by bcaller** [comment]
#130

**Comment by bcaller** [comment]
I think we use too many different templating languages and it is not possible to determine which one is being used as they do not use distinct filenames. Better to delete it and think again, potentially adding the rule to individual repositories where it would be helpful.
