### ISSUE TITLE
ERROR while installing `pip-audit` dependencies

### ISSUE THREAD

**Issue by thypon** [brave/security-action#160]
Reference: https://github.com/brave/brave-core/actions/runs/4688824778/jobs/8309802822?pr=17978

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
```

# Proposed Solution

- Investigate and fix the issue

**Comment by bcaller** [comment]
Can you show me the issue? That link doesn't show any problem.

**Comment by bcaller** [comment]
Separately there's some tfsec issue perhaps: https://github.com/brave/brave-core/actions/runs/4688719427/jobs/8309567404

**Comment by bcaller** [comment]
Oh I see, the run succeeded, it just complained:

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
semgrep 1.5.1 requires packaging~=21.0, but you have packaging 23.1 which is incompatible.
```

**Comment by thypon** [comment]
This should be fixed, I guess
