### ISSUE TITLE
Fix enabled flag

### ISSUE THREAD

**Issue by bcaller** [brave/security-action#212]
@thypon  Doesn't look like types can be used anymore. So enabled is the string "true". If you set the string to "false" then it is still truthy. So you need to do something like `input.enabled != 'false'`. Or change the API so it's `input.disabled` with no default.

_Originally posted by @bcaller in https://github.com/brave/security-action/issues/68#issuecomment-1599145123_

**Comment by thypon** [comment]
It seems to support value types in scripts. Maybe it's time to wrap them in scripts.

**Comment by thypon** [comment]
fixed
