### ISSUE TITLE
Ignore `clean | safe` in semgrep rulesets

### ISSUE THREAD

**Issue by thypon** [brave/security-action#23]
Cc @ecnmst

**Comment by thypon** [comment]
Seems to be a bug, since the `pattern-not-regex` is already contained https://github.com/brave/security-action/blob/main/assets/semgrep_rules/web/jinja_safe_usages.yaml#L21

**Comment by thypon** [comment]
Let's add a test and a fix for this issue

**Comment by bcaller** [comment]
No, it's a built-in semgrep issue from one of the p/* rulesets

**Comment by thypon** [comment]
Ah, I see!

**Comment by thypon** [comment]
I think we need a way to include the rule ID in the findings

**Comment by bcaller** [comment]
Found it! p/security-audit : python.flask.security.xss.audit.template-unescaped-with-safe.template-unescaped-with-safe
