### ISSUE TITLE
Github Actions not Pinned Rule

### ISSUE THREAD

**Issue by bcaller** [brave/security-action#309]
[semgrep] An action sourced from a third-party repository on GitHub is not pinned to a full length commit SHA. Pinning an action to a full length commit SHA is currently the only way to use an action as an immutable release. Pinning to a particular SHA helps mitigate the risk of a bad actor adding a backdoor to the action's repository, as they would need to generate a SHA-1 collision for a valid Git object payload.

Source: https://semgrep.dev/r/yaml.github-actions.security.third-party-action-not-pinned-to-commit-sha.third-party-action-not-pinned-to-commit-sha

# Proposed Solution

- [ ] Remove the rule or clarify Brave policy

What do you think? Unpinned actions are a genuine concern but to enforce this we need a system that checks for updates. And if you auto-accept the updates then that's the same as not pinning.

**Comment by thypon** [comment]
Indeed, we should verify the content - I think Socket.dev is already doing a pass on that, but I might be wrong.
In any case, even if we don't verify, the sole fact that we are using hashes, it makes more difficult, for an attacker to forge a malicious update.

In fact, with a hash is not possible to:
- define an update with hash X
- pointing tag A to hash X
- define a malicious update with hash Y
- pointing tag A to hash Y
- **perform the attack**
- rollback everything pointing tag A to hash X and deleting hash Y commit

**Comment by thypon** [comment]
On a side note, we should probably allowlist anything that is an aws-labs/github official action, since the attack is not really feasible
