### ISSUE TITLE
Port npm-audit to reviewdog

### ISSUE THREAD

**Issue by thypon** [brave/security-action#31]

**Comment by bcaller** [comment]
This will cause pain and suffering.

**Comment by thypon** [comment]
Most definetely. Consider though that `reviewdog` will just report issues in changed lines

**Comment by bcaller** [comment]
First challenge is that line numbers in the package/-lock.json aren't included in npm audit output. Would we want to figure out the line number so we can comment a particular line of package-lock.json?

**Comment by thypon** [comment]
Maybe we can get that out of grepping for the package name with the vuln
