### ISSUE TITLE
Disable rules for particular repos

### ISSUE THREAD

**Issue by bcaller** [brave/security-action#315]
I don't want this to be abused, but for brave.com it would be helpful to ignore certain rules such as templated hrefs.

**Comment by thypon** [comment]
I was reflecting re this issue, and I feel it should not be the repository to control which rule is disabled, but the rule itself.
I think I'll add a `metadata.allowlist` and a `metadata.blocklist` containing regexes of repo names we want, or we don't want to apply rules on.

**Comment by bcaller** [comment]
The incentive for devs to just block random rules is too high haha? Only issue could be disclosure of private repo names in the public security-action repo, but we can choose to ignore this.

**Comment by thypon** [comment]
More like I want to address this issue too https://github.com/brave/security-action/issues/47

Basically I need a rule that applies only to `brave` and `brave-intl` but none in `brave-experiments`

**Comment by thypon** [comment]
superseded by repo tagging, and rule based disable
