### ISSUE TITLE
Port pip-audit to reviewdog

### ISSUE THREAD

**Issue by thypon** [brave/security-action#32]

**Comment by bcaller** [comment]
Just a note: To work out what dependencies a python package has, you need to install the packages. Installation runs code from the package's `setup.py`. https://github.com/pypa/pip-audit#security-model. This means that altering a requirements.txt file in a PR would give you code exec in the security-action.

**Comment by bcaller** [comment]
Hmm we get output of the bugs per vulnerable package, but it doesn't say which package from requirements.txt caused that package to be included. Might run pip-audit per line of requirements.txt so that it's obvious where a vulnerability comes from. Perhaps it will be too slow.

**Comment by thypon** [comment]
Should we also check for `poetry` and other files format? I think we are already doing that on `search`

**Comment by thypon** [comment]
Fixed in 3072f251042921e24efb780d53d6525ea42f51f4
