### ISSUE TITLE
Suggest base::checked_cast() and IsValueInRangeForNumericType()

### ISSUE THREAD

**Issue by fmarier** [brave/security-action#347]
Could we suggest [these functions](https://github.com/brave/brave-core/pull/19946#discussion_r1329272481) in the GitHub message when [this rule](https://github.com/brave/security-action/blob/main/assets/semgrep_rules/c/cast-signed-to-unsigned.yaml) triggers?
![Screenshot from 2023-09-18 14-09-05](https://github.com/brave/security-action/assets/167821/21a96c1c-e070-46a2-b3cd-0234434ae6f7)

And we can link to https://chromium.googlesource.com/chromium/src/+/main/base/numerics/README.md.

**Comment by thypon** [comment]
Should we ping @bridiver every time this finding triggers, as well?
