### ISSUE TITLE
False positives with assignment operator used in `if` statement.

### ISSUE THREAD

**Issue by fmarier** [brave/security-action#388]
Could we suppress these warnings if the variable being assigned to is used within the block?
![Screenshot from 2023-10-05 09-58-56](https://github.com/brave/security-action/assets/167821/387cf965-7a83-440c-bcd0-22d117205b10)

Reference: https://github.com/brave/brave-core/pull/19965#discussion_r1347592676

# Proposed Solution

- [ ] Remove the rule
- [ ] Fork and improve the rule

**Comment by bcaller** [comment]
I'm struggling to reproduce this one locally actually...

**Comment by bcaller** [comment]
OK, that was because I was using semgrep 1.41 whereas now we are using 1.43 and the C++ support must've changed.

**Comment by bcaller** [comment]
I think it requires an update to https://github.com/brave/security-action/issues/391 ... I will try
