### ISSUE TITLE
Exclude "auto foo = some_value" from the wrong operator warnings

### ISSUE THREAD

**Issue by fmarier** [brave/security-action#391]
The presence of `auto` in `auto variable_name = ...` is a good sign that the assignment is intentional.

Reference: https://github.com/brave/brave-core/pull/20256/files/5b2666b35db73e6042bcefb29d356cae5cd9f1d2#r1347096453
![Screenshot from 2023-10-10 10-44-04](https://github.com/brave/security-action/assets/167821/c3d34c5f-e4e0-42e4-8db9-5412a0312f99)

# Proposed Solution

- [ ] Remove the rule
- [ ] Fork and improve the rule

**Comment by fmarier** [comment]
Also here: https://github.com/brave/brave-core/pull/20451/files/70c0b4023cd46b10aada5bd4ab06355ab2519268#r1349783182

**Comment by thypon** [comment]
The easiest fix here is to remove the support for C typos, and add the following ```        - pattern-not-inside: if ($TYPE $EXPR1 = $EXPR2) ...``` at line 42 of the typos rule
