### ISSUE TITLE
Exclude tests from "Artifactory token detected"

### ISSUE THREAD

**Issue by fmarier** [brave/security-action#392]
Reference: https://github.com/brave/brave-core/pull/20451#discussion_r1349790038
![Screenshot from 2023-10-10 10-53-07](https://github.com/brave/security-action/assets/167821/2cfd12d3-fbda-4d9f-b53e-c98d566c7dd6)

# Proposed Solution

- [ ] Remove the rule
- [ ] Fork and improve the rule

**Comment by thypon** [comment]
It won't trigger again,  since I added https://github.com/brave/brave-core/commit/168eecdd154982639b1ce74b5ff1103731167b12 yesterday
