### ISSUE TITLE
add rule for innerhtml/document.write 

### ISSUE THREAD

**Issue by diracdeltas** [brave/security-action#623]
these uses should always be audited by security team. sometimes they are in cpp files, not just js or html.

**Comment by thypon** [comment]
any example here?

**Comment by diracdeltas** [comment]
see https://github.com/brave/brave-core/blob/54e685f8e90eba4cfa7e7dda7a88a67c554278cb/ios/brave-ios/Sources/Brave/Frontend/UserContent/UserScripts/Sandboxed/MainFrame/AtDocumentStart/NoImageModeScript.js#L27

**Comment by diracdeltas** [comment]
another example here: https://github.com/brave/brave-core/blob/54e685f8e90eba4cfa7e7dda7a88a67c554278cb/browser/speedreader/speedreader_browsertest.cc#L302. though this is fine since it's a test.

**Comment by thypon** [comment]
From the example: evaluated strings in C++ might contain JS, which might contain vulnerabilities.

**Comment by thypon** [comment]
I'd replicate what is implemented in https://github.com/brave/brave-core/pull/24142 , as an MVP.
This might require a lift to something similar to the `sveltegrep` solution implemented by @bcaller , but for C++
