### ISSUE TITLE
Guidance for avoiding the use of `reinterpret_cast<T>`

### ISSUE THREAD

**Issue by cdesouza-chromium** [brave/security-action#685]
I have recently come across  several cases of unaligned reads done with using `reinterpret_cast`, and for these cases in particular where we are `reinterpret_cast`ing a value to read it is where I want us to be careful. These are usually numeric values.

In general, whatever we may be using `reinterpret_cast` for, the question first should be if there is something in `base/numerics/byte_conversions.h` that should be used instead.

Upstream has provided some guidance as well on avoiding `reinterpret_cast` [2].

A few examples of do's and don't's.

Wrong:
```c++
uint32_t value = *reinterpret_cast<const uint32_t*>(bytes.data());
```
Correct:
```c++
uint32_t value base::U32FromLittleEndian(bytes.first<4u>());
```

Wrong:
```c++
  const uint8_t* string_data =
      reinterpret_cast<const uint8_t*>(response_body.data());
  bytes_ =
      std::vector<uint8_t>(string_data, string_data + response_body.size());
```
Correct:
```c++
  bytes_ = base::ToVector(base::as_byte_span(response_body));
```

Wrong:
```c++
  std::string_view der_cert(reinterpret_cast<const char*>(cert->pbCertEncoded),
                            cert->cbCertEncoded);
```
Right:
```
  std::string_view der_cert = base::as_string_view(CertContextAsSpan(cert));
```

There are more examples in the the chromium docs topic about this [2].

It may be worth also warning on any uses of `void*`. It shouldn't be necessarily banned, but uses should be reviewed, because `void*` is usually not required, and its use necessarily requires the use of `reinterpret_cast`.

[1] https://source.chromium.org/chromium/chromium/src/+/main:base/numerics/byte_conversions.h
[2] https://chromium.googlesource.com/chromium/src/+/main/docs/unsafe_buffers.md#avoid-reinterpret_cast

**Comment by cdesouza-chromium** [comment]
@thypon Here's a list of other words we need to start catching:
  * `void*`
  * `UNSAFE_TODO`
  * `UNSAFE_BUFFERS`
  * `std::next`/`std::advance`/`std::prev`.

These should be flagged after https://github.com/brave/brave-core/pull/26027 is merged.

**Comment by thypon** [comment]
fixed in https://github.com/brave/security-action/pull/690
