### ISSUE TITLE
bfcdcb2fe1af7fa1cfe7c39d6806b5bef6a30d1f broke tests

### ISSUE THREAD

**Issue by thypon** [brave/security-action#78]
The commit bfcdcb2fe1af7fa1cfe7c39d6806b5bef6a30d1f renders tests extremely flaky.
Either we need to improve the test set, or the ruleset needs to be fixed.
At the current stage, I'm reverting this commit before running any test.

When trying to contact the GitHub API, the response code is 502

**Comment by bcaller** [comment]
This seems to have resolved itself, right?

**Comment by thypon** [comment]
Not really. It seems to happen because there are two jobs that are sending tons of duplicated findings altogether and the api collapse. It happens consistently if you copy the t3sts directory and start a job

**Comment by bcaller** [comment]
Is this affecting projects using security-action or just the security-action's self tests?

**Comment by thypon** [comment]
Just affecting the self-test. Basically it's a concurrency problem when the action is run multiple times. Maybe we can supersede this and not fixing it.
